---
 - name: Install and Launch Filebeat
   hosts: webservers
   become: true
   tasks:

   - name: download filebeat .deb file
     command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

   - name: install filebeat.deb
     command: dpkg -i filebeat-7.6.1-amd64.deb

   - name: Copy filebeat configuration
     copy:
       src: /etc/ansible/filebeat-config.yml
       dest: /etc/filebeat/filebeat.yml

   - name: Enable and Configure System Module
     command: filebeat modules enable system

   - name: Setup Filebeat
     command: filebeat setup

   - name: Start Filebeat Service
     command: service filebeat start

   - name: Enable Filebeat on Start
     systemd:
       name: filebeat
       enabled: yes