---
- name: Install and Configure Metricbeat
  hosts: webservers
  become: true
  tasks:

  - name: Download metricbeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install Metricbeat
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Copy metricbeat.yml
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable and Configure Metricbeat
    command: metricbeat modules enable system

  - name: Setup Metricbeat
    command: metricbeat setup

  - name: Start Metricbeat service
    command: service metricbeat start

  - name: Enable Metricbeat on start
    systemd:
        name: metricbeat
        enabled: yes